# -*- coding: utf-8 -*-
"""FileOrganiser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17GpDN5JkHfmzwSPo-U-yQdesFvmg2ePH
"""

import os, shutil

def organize(folder_path):
    file_types = {
        'Images': ['.png', '.jpg', '.jpeg'],
        'Documents': ['.pdf', '.docx', '.txt'],
        'Videos': ['.mp4', '.mov'],
        'Music': ['.mp3', '.wav'],
        'Others': []
    }

    for filename in os.listdir(folder_path):
        src = os.path.join(folder_path, filename)
        if os.path.isfile(src):
            ext = os.path.splitext(filename)[1].lower()
            moved = False
            for folder, extensions in file_types.items():
                if ext in extensions:
                    dest_folder = os.path.join(folder_path, folder)
                    os.makedirs(dest_folder, exist_ok=True)
                    shutil.move(src, os.path.join(dest_folder, filename))
                    moved = True
                    break
            if not moved:
                other = os.path.join(folder_path, 'Others')
                os.makedirs(other, exist_ok=True)
                shutil.move(src, os.path.join(other, filename))

folder = input("Enter the folder path to organize: ")
organize(folder)
print("✅ Files organized successfully!")